import { useEffect } from "react";
import { type NextPage } from "next";
import Head from "next/head";

import { type UserType } from "~/context/AuthContext";
import NavBar from "../components/Nav/NavBar";
import Window from "../components/Window/Window";
import MainGrid from "../components/Grid/Grid";

import { api, setToken } from "../utils/api";

const Home: NextPage = () => {
  useEffect(() => {
    const userCheck: string | null = localStorage.getItem("user");
    const user: UserType | null = userCheck ? JSON.parse(userCheck) : null; //eslint-disable-line
    if (user) {
      setToken(user.token);
    }
  }, []);
  return (
    <>
      <Head>
        <title>shawn81</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-site-gray-dark">
        <NavBar />
        <div className="flex grow flex-col items-center lg:flex-row lg:items-start lg:justify-center">
          <Window />
          <MainGrid />
        </div>
        <div className="bg-site-gray-med"></div>
      </main>
    </>
  );
};

export default Home;
