import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import NavBar from "../components/Nav/NavBar";
import LogInForm from "../components/SignIn/LogInForm";

import { api } from "../utils/api";

const LogInPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Log In</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-zinc-800">
        <NavBar />
        <LogInForm />
      </main>
    </>
  );
};

export default LogInPage;
