import { type NextPage } from "next";
import Head from "next/head";

import NavBar from "../components/Nav/NavBar";
import LogInForm from "../components/SignIn/LogInForm";

const LogInPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Log In</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-site-gray-dark">
        <NavBar />
        <LogInForm />
      </main>
    </>
  );
};

export default LogInPage;
