import { type NextPage } from "next";
import Head from "next/head";

import NavBar from "../components/Nav/NavBar";
import SignUpForm from "../components/SignIn/SignUpForm";

const SignUpPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-zinc-800">
        <NavBar />
        <SignUpForm />
      </main>
    </>
  );
};

export default SignUpPage;
